name: hackseeker-local

services:
  pb:
    build:
      context: pb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations
      - ./pb/pb_hooks:/pb/pb_hooks
    ports:
      - '8093:8090'

  meili:
    image: getmeili/meilisearch:latest
    ports:
      - '7703:7700'
    volumes:
      - ./meili/data:/meili_data
    env_file:
      - .env

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - ENV=${ENV}
  #   ports:
  #     - 3000:3000
